services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-net
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  message-generator:
    build: messageGenerator/.
    container_name: message-generator
    volumes:
      - ./Dataset_aliens:/app/images/pessoas
      - ./Dataset_times:/app/images/times
      - ./libs:/app/libs
    depends_on:
      - rabbitmq
    networks:
      - app-net
    restart: on-failure

networks:
  app-net:
    driver: bridge

volumes:
  rabbitmq_data:
